// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SportLog.Entities.Models;

[Index("SportId", Name = "IX_Game_SportId")]
public partial class Game
{
    [Key]
    public int Id { get; set; }

    [Column(TypeName = "Date")]
    public DateTime Date { get; set; }

    public int SportId { get; set; }

    [ForeignKey("SportId")]
    [InverseProperty("Game")]
    public virtual Sport Sport { get; set; }
}