// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportLog.API.Data;

#nullable disable

namespace SportLog.API.Migrations
{
    [DbContext(typeof(SportLogAppDbContext))]
    [Migration("20241004165547_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("SportLog.Entities.PseudoModels.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("SportId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SportId");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("SportLog.Entities.PseudoModels.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<sbyte>("BreakDuration")
                        .HasColumnType("INTEGER");

                    b.Property<sbyte>("MaxNumberOfPlayersByTeam")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<sbyte>("NumberOfPeriods")
                        .HasColumnType("INTEGER");

                    b.Property<sbyte>("NumberOfSubstitutionsByTeam")
                        .HasColumnType("INTEGER");

                    b.Property<sbyte>("NumberOfTeams")
                        .HasColumnType("INTEGER");

                    b.Property<sbyte>("PeriodDuration")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Sport");
                });

            modelBuilder.Entity("SportLog.Entities.PseudoModels.Game", b =>
                {
                    b.HasOne("SportLog.Entities.PseudoModels.Sport", "Sport")
                        .WithMany("Games")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("SportLog.Entities.PseudoModels.Sport", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
