// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using SportLog.Entities.Models;

namespace SportLog.API.Data;

public partial class SportLogAppDbContext : DbContext
{

    public SportLogAppDbContext(DbContextOptions<SportLogAppDbContext> options)
        : base(options)
    {
    }

    public SportLogAppDbContext()
    {

    }

    public virtual DbSet<Game> Games { get; set; }

    public virtual DbSet<Sport> Sports { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}